import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'
import './more.css'

const API_BASE = import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000'
const nav = [['cases','⌂','Active Cases'],['audit','▤','Audit Logs'],['pipeline','⌁','Pipeline Monitor'],['health','◉','System Health'],['settings','⚙','Operator Settings']]
const demoCases = [
  {case_id:'CASE-7F2A91C8',channel:'voice_call',language:'en',timestamp:'2026-09-15T12:41:02Z',status:'NEEDS_OPERATOR_REVIEW',svi_score:78,risk_tier:'HIGH',confidence:92,operator_confirmation_state:'PENDING'},
  {case_id:'CASE-5D39B141',channel:'chatbot',language:'hi',timestamp:'2026-09-15T12:22:47Z',status:'IN_REVIEW',svi_score:52,risk_tier:'MODERATE',confidence:88,operator_confirmation_state:'PENDING'},
  {case_id:'CASE-BC10A861',channel:'portal',language:'en',timestamp:'2026-09-15T11:56:11Z',status:'GUIDANCE_READY',svi_score:31,risk_tier:'LOW',confidence:95,operator_confirmation_state:'PENDING'}
]
const fallback = {transcript:'I’m calling because I don’t know where else to go. My name is [REDACTED] and I’m at [REDACTED]. I was told someone would be here again tonight. I’m scared they will find me.',recommendation:'Prioritize safety planning and a confidential support referral. Confirm an available location-safe contact path.'}
const auditRows = [
  ['12:41:07','CASE-7F2A91C8','—','Guidance Retrieved','Verified support pathway','HIGH','Human review required','—','RAG v1.4'],
  ['12:41:05','CASE-7F2A91C8','—','Risk Classified','SVI 78 · high priority','HIGH','—','—','SVI v2.1'],
  ['12:41:04','CASE-7F2A91C8','—','Evidence Fused','Redacted evidence bundle','—','—','—','Fusion v1.8'],
  ['12:22:51','CASE-5D39B141','OP-NHAA-042','Operator Confirmed','AI recommendation retained','MODERATE','Counselling pathway','CONFIRM','Console v1.0']
]
function Pill({children,tone='neutral'}){return <span className={`pill ${tone}`}>{children}</span>}
function Risk({risk}){return <Pill tone={(risk||'LOW').toLowerCase()}>{risk||'LOW'}</Pill>}
function Redacted({children}){return <span className="redacted">{children}</span>}
function PageTitle({eyebrow,title,subtitle,children}){return <header className="page-title"><div><p className="eyebrow"><span className="live-dot"/>{eyebrow}</p><h1>{title}</h1><span>{subtitle}</span></div>{children}</header>}
function Metric({label,value,tone='pink'}){return <div className="metric"><div><span>{label}</span><b>{value}%</b></div><div className="meter"><i className={tone} style={{width:`${value}%`}}/></div></div>}

function CaseReview({caseData}){
 const [action,setAction]=useState('CONFIRM'),[operator,setOperator]=useState('OP-NHAA-042'),[reason,setReason]=useState(''),[record,setRecord]=useState(''); const score=Math.round(caseData.svi_score||0); const transcript=fallback.transcript.split(/(\[REDACTED\])/g).map((x,i)=>x==='[REDACTED]'?<Redacted key={i}>REDACTED</Redacted>:x)
 return <section className="review-area"><div className="review-heading"><div><p className="eyebrow">CASE REVIEW / {caseData.case_id}</p><h2>Evidence, assessment & human authorization</h2></div><Risk risk={caseData.risk_tier}/></div><div className="review-grid">
  <article className="glass review-card"><h3>Intake & Evidence</h3><div className="data-grid"><span>Channel <b>{caseData.channel.replace('_',' ')}</b></span><span>Language <b>{caseData.language?.toUpperCase()}</b></span><span>Received <b>{new Date(caseData.timestamp).toLocaleString()}</b></span><span>Modalities <b>Text · Structured data</b></span></div><div className="privacy-line"><span>◈</span><div><b>Layer 1 privacy shield active</b><small>Transcript is redacted before assessment and operator display.</small></div></div><p className="transcript-text">{transcript}</p><div className="evidence-tags"><Pill tone="violet">Elevated urgency · 0.89</Pill><Pill tone="pink">Situational threat · 0.84</Pill><Pill>Location withheld</Pill></div></article>
  <article className="glass review-card assessment"><h3>AI Assessment <small>Operator review required</small></h3><div className="assessment-score"><strong>{score}</strong><span>Vulnerability / Distress<br/>Prioritization Score</span><Risk risk={caseData.risk_tier}/></div><Metric label="Assessment confidence" value={caseData.confidence||90}/><h4>Why this score?</h4><ul className="reason-list"><li><i/>Elevated distress language and repeated safety concern <b>0.89 confidence</b></li><li><i/>Contextual indicator matching a safety-planning trigger <b>0.84 confidence</b></li><li><i/>No critical override rule triggered <b>verified</b></li></ul><div className="critical"><span>Critical override</span><b>NOT TRIGGERED</b></div></article>
  <article className="glass review-card guidance"><h3>Service Guidance</h3><Pill tone="violet">AI-GENERATED GUIDANCE</Pill><h4>Confidential safety planning & support referral</h4><p>{fallback.recommendation}</p><div className="sop"><span>↗</span><div><small>VERIFIED PROCEDURAL GUIDANCE</small><b>NHAA SOP 4.2 · Immediate safety triage</b><em>Version 2026.3 · 94% relevance confidence</em></div></div><small className="disclaimer">AI-generated guidance — Operator review required.</small></article>
  <article className="glass review-card governance-full"><h3>Operator Governance <small>Human authorization required.</small></h3><div className="governance-grid"><label>OPERATOR ID<input value={operator} onChange={e=>setOperator(e.target.value)}/></label><div><span className="input-label">DECISION</span><div className="toggle"><button className={action==='CONFIRM'?'on-confirm':''} onClick={()=>setAction('CONFIRM')}>CONFIRM ACTION</button><button className={action==='OVERRIDE'?'on-override':''} onClick={()=>setAction('OVERRIDE')}>OVERRIDE DECISION</button></div></div></div>{action==='OVERRIDE'&&<div className="override-box"><span>Original AI Recommendation: <b>Confidential safety planning & support referral</b></span><label>FINAL OPERATOR DECISION<input placeholder="Specify authorized final pathway"/></label><label>OVERRIDE JUSTIFICATION<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required justification for override..."/></label></div>}<button className="execute" onClick={()=>setRecord(`${new Date().toLocaleTimeString()} · ${operator} · ${action}`)}>Record Operator Decision →</button>{record&&<p className="recorded">✓ Decision recorded in the prototype audit trail · {record}</p>}</article>
 </div></section>
}
function ActiveCases({cases,selected,setSelected,connected,refresh}){
 const [query,setQuery]=useState(''),[risk,setRisk]=useState('ALL'),[channel,setChannel]=useState('ALL'),[status,setStatus]=useState('ALL'); const filtered=useMemo(()=>cases.filter(c=>`${c.case_id} ${c.language}`.toLowerCase().includes(query.toLowerCase())&&(risk==='ALL'||c.risk_tier===risk)&&(channel==='ALL'||c.channel===channel)&&(status==='ALL'||c.status===status)),[cases,query,risk,channel,status])
 return <><PageTitle eyebrow={connected?'LIVE CASE QUEUE':'DEMO CASE QUEUE'} title="Active Cases" subtitle="AI-assisted case monitoring and operator review"><button className="soft-button" onClick={refresh}>↻ Refresh queue</button></PageTitle><section className="glass filter-bar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by case ID or language"/><select value={risk} onChange={e=>setRisk(e.target.value)}><option>ALL</option><option>LOW</option><option>MODERATE</option><option>HIGH</option><option>CRITICAL</option></select><select value={channel} onChange={e=>setChannel(e.target.value)}><option>ALL</option><option>voice_call</option><option>chatbot</option><option>portal</option></select><select value={status} onChange={e=>setStatus(e.target.value)}><option>ALL</option><option>NEEDS_OPERATOR_REVIEW</option><option>IN_REVIEW</option><option>GUIDANCE_READY</option></select><button className="date-filter">▣ Sep 15, 2026</button></section><section className="glass case-table-wrap"><table className="case-table"><thead><tr><th>CASE / INTAKE</th><th>LANGUAGE</th><th>RECEIVED</th><th>PRIORITIZATION</th><th>RISK TIER</th><th>CONFIDENCE</th><th>OPERATOR REVIEW</th><th/></tr></thead><tbody>{filtered.map(c=><tr key={c.case_id} className={selected?.case_id===c.case_id?'selected-row':''} onClick={()=>setSelected(c)}><td><b>{c.case_id}</b><small>{c.channel.replace('_',' ')}</small></td><td>{c.language?.toUpperCase()||'—'}</td><td>{new Date(c.timestamp).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</td><td><strong className="score">{Math.round(c.svi_score||0)}</strong><small> / 100</small></td><td><Risk risk={c.risk_tier}/></td><td>{c.confidence||90}%</td><td><Pill tone={c.operator_confirmation_state==='PENDING'?'waiting':'success'}>{(c.operator_confirmation_state||'PENDING').replace('_',' ')}</Pill></td><td><button className="row-open">Review →</button></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">No cases match the active filters.</div>}</section>{selected&&<CaseReview caseData={selected}/>}</>
}
function AuditLogs(){const [query,setQuery]=useState(''),[detail,setDetail]=useState(null);const rows=auditRows.filter(r=>r.join(' ').toLowerCase().includes(query.toLowerCase()));return <><PageTitle eyebrow="APPEND-ONLY OPERATIONAL RECORD" title="Audit Logs" subtitle="Traceable record of model outputs, evidence, recommendations and operator decisions"/><section className="glass filter-bar audit-filter"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search case, operator, event type or configuration"/><button className="date-filter">Event type: All</button><button className="date-filter">Export record ↗</button></section><section className="glass case-table-wrap"><table className="case-table audit-table"><thead><tr>{['TIMESTAMP','CASE ID','OPERATOR','EVENT TYPE','AI OUTPUT','RISK','RECOMMENDATION','HUMAN DECISION','CONFIG'].map(h=><th key={h}>{h}</th>)}<th/></tr></thead><tbody>{rows.map((r,i)=><tr key={i} onClick={()=>setDetail(r)}>{r.map((x,j)=><td key={j}>{j===5?<Risk risk={x}/>:j===7&&x!=='—'?<Pill tone="success">{x}</Pill>:x}</td>)}<td><button className="row-open">View →</button></td></tr>)}</tbody></table></section>{detail&&<aside className="audit-drawer"><button onClick={()=>setDetail(null)}>×</button><p className="eyebrow">AUDIT EVENT DETAIL</p><h2>{detail[3]}</h2><Pill tone="violet">{detail[8]}</Pill><div className="drawer-lines"><span>Input / context <b>{detail[1]} · privacy-safe evidence bundle</b></span><span>Evidence used <b>Redacted transcript, fusion markers, intake metadata</b></span><span>AI assessment <b>{detail[4]} · {detail[5]} risk tier</b></span><span>Retrieved guidance <b>{detail[6]}</b></span><span>Human operator decision <b>{detail[7]}</b></span><span>Timestamp <b>2026-09-15 {detail[0]} UTC</b></span></div><p className="disclaimer">AI Recommendation and Human Operator Decision are distinct audit events.</p></aside>}</>}
function Pipeline(){const stages=[['Layer 0','Intake Ingested','COMPLETED','12:41:02','Portal text · consent declaration','—'],['Layer 1','Privacy / PII Redaction + Evidence Fusion','COMPLETED','12:41:04','Redacted transcript · evidence bundle','0.94'],['Layer 2','Vulnerability / Distress Assessment','COMPLETED','12:41:05','SVI 78 · contributing evidence','0.92'],['Risk & Triage','Risk tier classified','COMPLETED','12:41:05','HIGH · operator review required','0.92'],['Layer 4','Service Guidance / SOP Retrieval','COMPLETED','12:41:06','NHAA SOP 4.2 matched','0.94'],['Governance','Operator Review','WAITING','12:41:07','Awaiting human authorization','—'],['Outcome','Confirmed Service Pathway','WAITING','—','No action executed','—']];return <><PageTitle eyebrow="OBSERVABILITY / NO AUTONOMOUS ROUTING" title="Pipeline Monitor" subtitle="End-to-end case processing visibility"/><section className="monitor-stats">{[['42ms','Processing latency'],['18','Cases processed'],['3','Awaiting review'],['0','Failed stages']].map(([v,l])=><article className="glass stat-card" key={l}><strong>{v}</strong><span>{l}</span></article>)}</section><div className="pipeline-layout"><section className="pipeline-list">{stages.map((s,i)=><React.Fragment key={s[1]}><article className="glass stage-card"><span className="stage-number">{String(i+1).padStart(2,'0')}</span><div><small>{s[0]}</small><h3>{s[1]}</h3><p>{s[4]}</p></div><div className="stage-meta"><Pill tone={s[2]==='COMPLETED'?'success':'waiting'}>{s[2]}</Pill><span>{s[3]}</span><b>{s[5]!=='—'&&`Confidence ${s[5]}`}</b></div></article>{i<stages.length-1&&<div className="stage-line"/>}</React.Fragment>)}</section><aside className="glass activity"><p className="eyebrow">LIVE PIPELINE ACTIVITY</p><h3>Case VC-2048</h3>{['[12:41:02] Case VC-2048 received','[12:41:03] PII redaction completed','[12:41:04] Evidence fusion completed','[12:41:05] SVI evaluated','[12:41:05] Risk tier classified: HIGH','[12:41:06] SOP guidance retrieved','[12:41:07] Awaiting operator review'].map(x=><p className="activity-line" key={x}><i/> {x}</p>)}<div className="activity-note">Observability only. No service pathway is executed without human authorization.</div></aside></div></>}
function SystemHealth(){const services=[['Input / Intake','HEALTHY','12ms','0'],['Evidence Fusion','HEALTHY','44ms','0'],['SVI Engine','HEALTHY','18ms','0'],['Risk / Triage','HEALTHY','6ms','0'],['Service / RAG','WARNING','210ms','1'],['Audit Logging','HEALTHY','9ms','0'],['Case Storage','HEALTHY','14ms','0']];return <><PageTitle eyebrow="PRODUCTION OBSERVABILITY" title="System Health" subtitle="Infrastructure and AI service availability"/><section className="health-summary">{[['HEALTHY','Overall system status'],['HEALTHY','API status'],['HEALTHY','Intake gateway'],['HEALTHY','Evidence / Fusion'],['HEALTHY','SVI engine'],['WARNING','RAG / SOP service'],['HEALTHY','Case storage'],['HEALTHY','Audit logging']].map(([v,l])=><article className="glass health-mini" key={l}><Pill tone={v==='WARNING'?'warning':'success'}>{v}</Pill><span>{l}</span><i/></article>)}</section><section className="health-metrics"><article className="glass health-chart"><p className="eyebrow">API PERFORMANCE</p><h3>Request throughput <b>128/min</b></h3><div className="bars">{[40,57,42,78,61,89,70,96,75,68,82,92,74,63,88,58,71,80].map((v,i)=><i key={i} style={{height:`${v}%`}}/>)}</div><div className="chart-foot"><span>API latency <b>42ms</b></span><span>Error rate <b>0.2%</b></span><span>Last success <b>now</b></span></div></article><article className="glass health-chart"><p className="eyebrow">PROCESSING QUEUE</p><h3>Active cases <b>3</b></h3><div className="queue-ring"><strong>3</strong><span>awaiting<br/>review</span></div><div className="chart-foot"><span>Storage <b>available</b></span><span>Queue age <b>01:18</b></span></div></article></section><section className="service-grid">{services.map(s=><article className="glass service-card" key={s[0]}><div><h3>{s[0]}</h3><Pill tone={s[1]==='WARNING'?'warning':'success'}>{s[1]}</Pill></div><span>Last checked: 12:43:18 UTC</span><div><b>{s[2]} latency</b><b>{s[3]} errors</b><i/></div></article>)}</section><section className="glass system-events"><p className="eyebrow">RECENT SYSTEM EVENTS</p>{['Evidence service recovered · 12:40:16','RAG response latency increased · 12:38:42','Audit logging operational · 12:35:06','Intake gateway healthy · 12:31:29'].map((x,i)=><p key={x}><i className={i===1?'warning-dot':''}/> {x}</p>)}</section></>}
function Settings(){return <><PageTitle eyebrow="AUTHORIZED OPERATOR ACCESS ONLY" title="Operator Settings" subtitle="Secure console preferences and session information"/><div className="settings-grid"><article className="glass settings-card"><h3>Operator Profile</h3><div className="profile-row"><div className="operator-avatar">AP</div><div><b>A. Pandey</b><small>NHAA Operations · Crisis Response Unit</small></div><Pill tone="success">SESSION ACTIVE</Pill></div><label>OPERATOR ID<input value="OP-NHAA-042" readOnly/></label><label>ROLE<input value="Authorized Case Review Operator" readOnly/></label><label>ORGANIZATION / UNIT<input value="NHAA · Regional Operations" readOnly/></label></article><article className="glass settings-card"><h3>Dashboard Preferences</h3><label>DEFAULT LANDING PAGE<select><option>Active Cases</option><option>Pipeline Monitor</option></select></label><div className="settings-switch"><span>Comfortable density<small>Use relaxed table and panel spacing.</small></span><button className="switch on"/></div><label>AUTO-REFRESH INTERVAL<select><option>30 seconds</option><option>60 seconds</option><option>Manual</option></select></label><div className="settings-switch"><span>Operational notifications<small>Show service warnings and review-ready cases.</small></span><button className="switch on"/></div></article><article className="glass settings-card"><h3>Review Preferences</h3><label>DEFAULT CASE FILTER<select><option>All risk tiers</option><option>High and critical</option></select></label><div className="settings-switch"><span>Show evidence confidence<small>Display confidence beside contributing evidence.</small></span><button className="switch on"/></div><div className="settings-switch"><span>Expanded audit details<small>Open event context in the audit drawer.</small></span><button className="switch"/></div></article><article className="glass settings-card security"><h3>Security & Access</h3><div className="security-lines"><span>Authentication <b>Verified session</b></span><span>Access level <b>Operator review · restricted</b></span><span>Last login <b>2026-09-15 09:12 UTC</b></span><span>Session expiry <b>Masked / managed by identity provider</b></span></div><p>Authorized operator access only. This prototype does not expose or store real credentials.</p></article></div></>}
function App(){const [page,setPage]=useState('cases'),[cases,setCases]=useState(demoCases),[selected,setSelected]=useState(demoCases[0]),[connected,setConnected]=useState(false);async function refresh(){try{const r=await fetch(`${API_BASE}/cases`);if(!r.ok)throw Error();const p=await r.json();const list=Array.isArray(p)?p:p?.cases||[];if(list.length){setCases(list);setSelected(list[0]);setConnected(true)}else setConnected(false)}catch{setConnected(false)}}useEffect(()=>{refresh()},[]);const View=page==='cases'?<ActiveCases cases={cases} selected={selected} setSelected={setSelected} connected={connected} refresh={refresh}/>:page==='audit'?<AuditLogs/>:page==='pipeline'?<Pipeline/>:page==='health'?<SystemHealth/>:<Settings/>;return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="pulse"/><div><strong>VOICE CIPHER</strong><small>NHAA OPERATIONAL DASHBOARD</small></div></div><nav>{nav.map(([id,icon,label])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><span>{icon}</span>{label}{id==='cases'&&<em>{cases.length}</em>}</button>)}</nav><div className="sidebar-bottom"><div className="operator-avatar">AP</div><div><b>A. Pandey</b><small>Authorized operator · Shift A</small></div><span className="online"/></div></aside><section className="workspace"><div className="top-actions"><span className="api-state">{connected?'LIVE API':'DEMO MODE'}</span><span className="api-state">◈ AUTHORIZED SESSION</span></div><div className="view-shell" key={page}>{View}</div></section></main>}
createRoot(document.getElementById('root')).render(<App />)
